name: FewShot-Learning Model CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: fewshot-env
          auto-activate-base: false

      - name: Install pip dependencies (if any)
        run: |
          conda activate fewshot-env
          pip install -r requirements.txt || true

      - name: Check Python version
        run: |
          conda activate fewshot-env
          python --version

      - name: Lint with flake8
        run: |
          conda activate fewshot-env
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests (import check)
        run: |
          conda activate fewshot-env
          python -c "import data; import prototypical_network"

      - name: Run train script (smoke test)
        run: |
          conda activate fewshot-env
          python train.py --epochs 1 --num_shots 1 --batch_size 2

      - name: Run test script (smoke test)
        run: |
          conda activate fewshot-env
          python test.py --num_shots 1 --batch_size 2 