name: FewShot-Learning Model CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: fewshot-env
          auto-activate: false

      - name: Install pip dependencies (if any)
        run: pip install -r requirements.txt || true
        shell: bash -l {0}

      - name: Check Python version
        run: python --version
        shell: bash -l {0}

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        shell: bash -l {0}

      - name: Run tests (import check)
        run: python -c "import data; import prototypical_network"
        shell: bash -l {0}

      - name: Run train script (smoke test)
        run: python train.py --epochs 1 --num_shots 1 --batch_size 2
        shell: bash -l {0}

      - name: Run test script (smoke test)
        run: python test.py --num_shots 1 --batch_size 2
        shell: bash -l {0}